language: cpp
dist: xenial
notifications:
  email: false

# Define builds on mulitple OS/compiler combinations.
# Feel free to add/remove entries from this list.
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
            - kcov
            - g++-7
            - doxygen
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7; sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90"

before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build

install:
  - cd $PARENTDIR/build
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Debug
  - make

script:
  - make
  # - make test

after_success:
  - cd $PARENTDIR/build
  - ctest
  - bash <(curl -s https://codecov.io/bash)
